version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project/microcommerce
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build and Test
          command: mvn -B clean package

  deploy-docker-image:
    # On utilise une machine virtuelle complète pour éviter les erreurs de "Remote Docker"
    machine:
      image: ubuntu-2204:2024.01.1 
    working_directory: ~/project/microcommerce
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build and Push Docker Image
          command: |
            # Connexion sécurisée à Azure
            echo "$DOCKER_PASS" | docker login microcommerce.azurecr.io -u "$DOCKER_USER" --password-stdin
            
            # Construction de l'image (le Dockerfile s'occupe de tout)
            docker build -t microcommerce.azurecr.io/microcommerce:latest .
            
            # Envoi vers Azure
            docker push microcommerce.azurecr.io/microcommerce:latest
      
       # --- FORCING AZURE TO UPLOAD (TO PULL) THE LATEST IMAGE ---
      - run:
          name: Trigger Azure Webhook (Force Pull)
          command: |
            # On envoie un signal à Azure pour lui dire de télécharger la nouvelle image
            curl -X POST "$AZURE_WEBHOOK_URL"

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - deploy-docker-image:
          requires:
            - build-and-test