version: 2.1
orbs:
  docker: circleci/docker@2.1.4
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project/microcommerce
    steps:
      - checkout:
         path: ~/project
         
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - persist_to_workspace:
         root: target
         paths:
            - "*.jar"

  deploy-docker-image:
    docker:
       - image: cimg/base:stable
    resource_class: medium
    working_directory: ~/project/microcommerce
    steps:
      - checkout:
         path: ~/project
      - setup_remote_docker:
          version: default
          docker_layer_caching: false
      - attach_workspace:
          at: target
      - run:
          name: "Build and push Docker image"
          command: 
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin microcommerce.azurecr.io
            docker build -t microcommerce.azurecr.io/microcommerce:latest .
            docker push microcommerce.azurecr.io/microcommerce:latest

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - deploy-docker-image:
          requires:
            - build-and-test